name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  test:
    name: Test
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Run tests
      run: dotnet test --no-build --configuration Release --verbosity normal

  publish:
    name: Publish Native Executable
    runs-on: windows-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Publish Native AOT
      run: dotnet publish src/PowerShellArgumentCompleter.csproj -c Release -r win-x64 -o publish

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: pwsh-argument-completer-win-x64
        path: publish/pwsh-argument-completer.exe
        if-no-files-found: error

  release:
    name: Release Build
    runs-on: windows-latest
    needs: test
    if: github.event_name == 'release'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Publish Native AOT
      run: dotnet publish src/PowerShellArgumentCompleter.csproj -c Release -r win-x64 -o publish

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./publish/pwsh-argument-completer.exe
        asset_name: pwsh-argument-completer.exe
        asset_content_type: application/octet-stream
